language: ruby
branches:
	only:
	- master
rvm:
- 2.4.2
before_install:
 - gem update --system 2.4.1
 - gem install bundler 1.16.0
before_script:
- chmod +x ./cibuild
script: ./cibuild
exclude: [vendor]
sudo: false
