language: ruby
rvm: 2.6
install: bundle install
before_script:
  - git config --global user.email "malecki.maciej@gmail.com"
  - git config --global user.name "Maciej Malecki"
  - git remote rm origin
  - git remote add origin https://maciejmalecki:${GH_TOKEN}@github.com/maciejmalecki/blog.git
script: JEKYLL_ENV=production bundle exec rake site:deploy
env:
  global:
    secure: mJBS4ZQ5nyT2gi1/cNzqBFJWS8WE/fE14oVKe9h4r12OCNQtsHoJmey+5iah86ga5ebluRcyihPlyIbkjVBr5nL7rOoWMvUOQjGBS7RvANY8eERjhpUSuDFoZBlyC6t5XnHwVH2/usKXa7diJVAzqIKFvqkLkZhiooQFsWrpZioZQcQkQUDNs180PqxjPH0HqcbVnL1NaGsgTHTR/SmuVAbyNxsx/8Vr6ErKLF9TPN+sD7HX/qP4TPj+/lOvxfbB/TpOy5DS5tbdhocHr4YVxZetug/c0akmziSKgma3pCmh3ZrYGNGDtmFQmb90/sLdjnW2GeEUd5UItAdWYBJQjo+G3Mpl8uOCfGqupvN5dmSRYwfOj+IGQ5Qf+XWnPx/c+JWS7qttfItTBbJ/FJqcpkttPM6rtH2YMlAAeJmBVB9Jm+u62duVUv2oj/GYsPiauZ1OG59SWhyguqEsQHU5AnYzAhllbmhpho+A1NBOBE24BMKRXdiDPmlwy6XaWGshyCeDDMnQXNGHNt4mWEbMoHR6iKafmM4J6kCn5vW7ABHCzRRVZC+MI1V+/RkvJskSA4ZSnfHRLyxXWshUWS8jcm98gQDgRJkcwlfoZRWT3XiVuMdvTdGU/5hTLbvn7OngBz5dft2G4GcZ0DPAhmAoObjWhbGL01XgXlV5EvgfmZ4=
