language: ruby
rvm: 2.2
install: bundle install
script: JEKYLL_ENV=production bundle exec rake site:deploy
env:
  global:
    secure: "azviKdO+TopwuZg/H2na3CLNxvWhgCyR1uhFuCkpWEneaMWei0AKYwoHiQF0YdT6Oz9UoT+bnA8OFDOT2LtgV+DkVRIcauWgAtnmDBQkw7dUy48tBhwb8CsRQ4YGNCIxvnjyGLHdaC9rspzwSLmJ+Q6b0UDkLpXcu87OPGq9y83Q3sZtfJShLGH28KYIm4+S/FzcwDiAOMckfNHgY4zQhW3IGf4nfCt77x2mgQQ0M9UGBurYDqMGQ7raP0D+xjiueO2JAx6KOLTs7ygyoxOVgDbi2UHQ87k+zQkRjSJMEwJTtvjIp93SNlEevnlzuj7KiUsQwN0LrkzXZfD7S8RoKrPazJh4A36/a1eFfPndMKqs3jTPIOK3fJt9s1cmBbwOZk9JCKZmWcZJyI4FCKoIDwMFWaYZ+zqvYf9GGB/rkzh/24Upf6oYU8FpwvQlzb40ASOXAAzrO0Rql2Yd4nWgGMIcr4HI9IcyMD+JJ4zK9PRR2GsKQ2z4QTeUiPleUegZSRZ++dPNH1imf/6GslCyxMTfJjLvxNw0/sL0s8RRTkwh0TNqGs4WK000UUB9lzRpUVvvUem/WFtTDJTmQMdfp1dKmJxaq4Oox9ffmTQ5SdHDTMzvgs5LR1vvn3SOKKT3o1eK/bf/7GekFyLzjTW/qQ+caUvuXBGkGEsrkN77QMA="
