language: ruby
branches:
	only:
	- master
rvm:
- 2.4.2
before_install:
 - gem update --system
 - gem install bundler
 - bundle update rake
 - bundle install
before_script:
- chmod +x ./cibuild
script: ./cibuild
exclude: [vendor]
sudo: false
