language: ruby
branches:
	only:
	- master
rvm:
- 2.2.3
before_install:
 - bash -c "yes | gem uninstall -i /home/travis/.rvm/gems/ruby-2.5.0@global rake"
before_script:
- chmod +x ./cibuild
script: ./cibuild
exclude: [vendor]
sudo: false
